# Generated by Django 4.2.7 on 2024-11-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=0, verbose_name='Пробег'),
        ),
    ]
